name: Rust

on:
  push:
    branches: [ '**' ]
  schedule:
    - cron: '0 0 1 * *'
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --release --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: writeup-export
          path: target/release/writeup-export